### ISSUE TITLE
Package request: pihole-FTL 

### ISSUE THREAD

**Issue by debiansid** [DDoSolitary/alpine-repo#10]
Hi
Would you please add pihole-FTL for Alpine Linux? Thanks
https://github.com/pi-hole/FTL/issues/552#issuecomment-484722140

**Comment by DDoSolitary** [comment]
Hi, I'm happy to add it, but after some research I found out that the software won't build in Alpine without the changes in the `tweak/musl_support` branch. So I can't add it until the branch is merged and released.

**Comment by debiansid** [comment]
Or you can do git patch to make it work.

**Comment by DDoSolitary** [comment]
Just tried to compile the branch and it failed:

```
signals.c:12:10: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h>
          ^~~~~~~~~~~~
```

**Comment by DDoSolitary** [comment]
<del>Build completed successfully</del> on v4.2.3 (with patching) after `apk add libexecinfo-dev`

Now it's another error:

```
In file included from dnsmasq/dnsmasq.h:98,
                 from dnsmasq_interface.c:11:
/usr/include/sys/poll.h:1:2: error: #warning redirecting incorrect #include <sys/poll.h]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^~~~~~~
cc1: all warnings being treated as errors
```

**Comment by debiansid** [comment]
```
dnsmasq.h:98 
change it into 
#include<poll.h>
```

**Comment by DDoSolitary** [comment]
Yeah I know, just proposed in the upstream issue earlier.

**Comment by DDoSolitary** [comment]
Done.
