### ISSUE TITLE
request shadowsocks-libev trunk 

### ISSUE THREAD

**Issue by debiansid** [DDoSolitary/alpine-repo#11]
hi
just in case we want to test new feature like this
shadowsocks/shadowsocks-libev#2360
I am asking for setting up new package like shadowsocks-libev-trunk which we can set some specific commit to build.

https://github.com/DDoSolitary/alpine-repo/issues/9 
is too old

thanks

**Comment by DDoSolitary** [comment]
No, I won't package any unreleased code without an appropriate reason (e.g. the release doesn't work on Alpine). If you just want to try the latest code, you should either build it yourself (`make && make install`) or wait until it gets released. It's not the correct way to ask a packager to build it for you.

**Comment by DDoSolitary** [comment]
#9 isn't outdated at all. If you want an up-to-date package, you can simply update `pkgver`/`pkgrel` and `abuild` will do the rest for you.
