### ISSUE TITLE
Dockerfiles

### ISSUE THREAD

**Issue by vincent-tr** [DDoSolitary/alpine-repo#15]
Hi,

Your cross-platform build tools look very interesting!
Would you mind sharing your Dockerfiles used to build your docker images https://hub.docker.com/r/ddosolitary/alpine-builder ?

Thanks

**Comment by DDoSolitary** [comment]
It is already available in the `docker` branch: https://github.com/DDoSolitary/alpine-repo/tree/docker

**Comment by vincent-tr** [comment]
Thanks a lot, I did not notice it!
