### ISSUE TITLE
package request netfilter-fullcone nat 

### ISSUE THREAD

**Issue by debiansid** [DDoSolitary/alpine-repo#16]
Source code 
`https://github.com/Chion82/netfilter-full-cone-nat`
Arch Linux package 
`https://www.archlinux.org/packages/community/x86_64/netfilter-fullconenat/`
`https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=iptables-fullcone-nat`

**Comment by DDoSolitary** [comment]
Sorry, the project doesn't provide releases and I don't want to package from git master. Currently this repo doesn't have any auto-updating mechanisms and it will be too much work to track git commits manually.
